- name: "Humid Sensor"
  device_class: "humidity"
  suggested_display_precision: 1
  unique_id: "humid_sensor"
  state_topic: "home/sensor/humidity"
  unit_of_measurement: "%"
  value_template: "{{ value | float }}"