# Use the official Eclipse Mosquitto image as the base image
FROM eclipse-mosquitto:latest

# Expose the default MQTT ports
EXPOSE 1883 9001

RUN chmod -R 777 /mosquitto

# Start Mosquitto
CMD ["mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]