
services:
  homeassistant:
    container_name: hass
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - "8123:8123"
    volumes:
      - ./hass:/config
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - ha

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"  # RTSP port
      - "8888:8888"  # WebRTC HTTP port
      - "8889:8889/udp"  # WebRTC ICE port
    volumes:
      - ./mediamtx:/config  # Lưu cấu hình MediaMTX
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=172.27.192.1
    restart: unless-stopped
    networks:
      - ha

  mosquitto:
    container_name: hass-mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
    networks:
      - ha
  # component:
  #   build: ./component
  #   depends_on:
  #     - mosquitto
  #   restart: unless-stopped
  mqtt_pipeline:
    build: ./pipeline
    depends_on:
      - mosquitto
    restart: unless-stopped
    networks:
      - ha

networks:
  ha:
    driver: bridge