
services:
  homeassistant:
    container_name: hass
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - "8123:8123"
    volumes:
      - ./hass:/config
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - TZ=Asia/Ho_Chi_Minh

  mosquitto:
    container_name: hass-mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
  component:
    build: ./component
    depends_on:
      - mosquitto
    restart: unless-stopped
