- id: '1745157257921'
  alias: Turn on cooling mode
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.temperature
    above: 30
    for:
      hours: 0
      minutes: 0
      seconds: 1
  conditions:
  - condition: state
    state: home
    entity_id: device_tracker.member
  actions:
  - action: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: cool
    target:
      entity_id: climate.living_room_conditioner
  - action: climate.set_preset_mode
    metadata: {}
    data:
      preset_mode: home
    target:
      entity_id: climate.living_room_conditioner
  - action: climate.set_temperature
    metadata: {}
    data:
      temperature: 16
      hvac_mode: cool
    target:
      entity_id: climate.living_room_conditioner
  mode: single
- id: '1745158517325'
  alias: Turn off devices while no one home
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - device_tracker.member
    from: home
    to: not_home
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data:
      transition: 2
    target:
      entity_id: light.living_room_light
  - action: climate.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: climate.living_room_conditioner
  mode: single
- id: '1745158830677'
  alias: Get Home member
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - device_tracker.member
    to: home
    from:
  conditions:
  - condition: numeric_state
    entity_id: sensor.temperature
    above: 30
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.living_room_light
  - action: climate.set_hvac_mode
    metadata: {}
    data:
      hvac_mode: cool
    target:
      entity_id: climate.living_room_conditioner
  - action: lock.lock
    metadata: {}
    data:
      code: '0000'
    target:
      entity_id: lock.front_door_lock
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 55
    target:
      entity_id: light.living_room_light
  mode: single
- id: '1748614849274'
  alias: camera notification
  description: ''
  triggers:
  - trigger: mqtt
    topic: home/frontdoor/notifications
  conditions:
  - condition: template
    value_template: '{{ trigger.payload_json.timestand != 0 }}'
  actions:
  - action: persistent_notification.create
    metadata: {}
    data:
      title: Frontdoor Camera - {{ now().strftime('%B %d %H:%M') }}
      message: '{{ trigger.payload_json.name | title }} detected and standing for
        {{trigger.payload_json.timestand}}'
      notification_id: frontdoor_camera_{{ trigger.payload_json.name | lower }}
  mode: single
- id: '1748681697677'
  alias: Stove open warning
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.people_detection
    from:
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  conditions:
  - condition: or
    conditions:
    - condition: state
      state: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
      entity_id: switch.gas_stove_left
    - condition: state
      state: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
      entity_id: switch.gas_stove_right
    - condition: state
      state: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
      entity_id: switch.gas_stove_mid
  actions:
  - action: persistent_notification.create
    data:
      title: Active Stove Warning!!! - {{ now().strftime('%B %d %H:%M') }}
      message: 'Stoves are still on, but no one is detected in the kitchen.

        '
  mode: single
- id: '1748704185401'
  alias: Clear empty notification
  description: ''
  triggers:
  - trigger: persistent_notification
    update_type:
    - updated
    - current
    - removed
    - added
  conditions:
  - condition: template
    value_template: '{{ trigger.notification.notification_id.startswith(''frontdoor_camera_'')
      }}'
    enabled: true
  - condition: template
    value_template: '{{ trigger.notification.message.endswith(''0 second'') }}'
  actions:
  - action: persistent_notification.dismiss
    metadata: {}
    data:
      notification_id: '{{ trigger.notification.notification_id}}'
  mode: single
- id: '1748932858082'
  alias: High temperature warning
  description: ''
  triggers:
  - trigger: mqtt
    topic: home/sensor/temperature
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ 31 <= (trigger.payload | float) <= 35 }}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Unhealthy high temperature
          title: Temperature Warning!!!
          notification_id: high_temp_warning
      - action: climate.set_temperature
        metadata: {}
        data:
          temperature: 21
          hvac_mode: cool
        target:
          entity_id:
          - climate.bedroom_room_conditioner_1_2
          - climate.bedroom_room_conditioner_1
          - climate.living_room_conditioner
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Adjust air conditioner down to 21°C
          title: Cooling mode activated!
          notification_id: hvac_activated
    - conditions:
      - condition: template
        value_template: '{{ 35 < (trigger.payload | float) <= 45.0 }}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Hazardous high temperature
          title: Temperature Warning!!!
          notification_id: high_temp_warning
      - action: climate.set_temperature
        metadata: {}
        data:
          temperature: 21
          hvac_mode: cool
        target:
          entity_id:
          - climate.bedroom_room_conditioner_1_2
          - climate.bedroom_room_conditioner_1
          - climate.living_room_conditioner
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Adjust air conditioner down to 21°C
          title: Cooling mode activated!
          notification_id: hvac_activated
  mode: single
- id: '1748934631877'
  alias: Humidity warning
  description: ''
  triggers:
  - trigger: mqtt
    topic: home/sensor/humidity
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ 20 < (trigger.payload | float) <= 30}}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Unhealthy low humidity
          title: Humidity Warning!!!
          notification_id: low_humidity_warning
    - conditions:
      - condition: template
        value_template: '{{0 <= (trigger.payload | float) <= 20}}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Hazardous low humidity
          title: Humidity Warning!!!
          notification_id: low_humidity_warning
    - conditions:
      - condition: template
        value_template: '{{80 < (trigger.payload | float) <= 100}}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Hazardous high humidity
          title: Humidity Warning!!!
          notification_id: high_humidity_warning
    - conditions:
      - condition: template
        value_template: '{{ 70 < (trigger.payload | float) <= 80}}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Unhealthy high humidity
          title: Humidity Warning!!!
          notification_id: high_humidity_warning
  mode: single
- id: '1748948977924'
  alias: Gas leaking warning
  description: ''
  triggers:
  - trigger: mqtt
    topic: home/sensor/gas_concentration
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ 400 <= trigger.payload | float}}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          title: Gas Leaking Warning!!!
          notification_id: gas_leaking_warning
          message: ' '
  mode: single
- id: '1748949370424'
  alias: PM2.5 warning
  description: ''
  triggers:
  - trigger: mqtt
    topic: home/sensor/pm25
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ 35.5 <= (trigger.payload | float) <= 55.4 }}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Unhealthy air quality due to elevated PM2.5 concentration
          notification_id: pm2.5_warning
          title: Air quality warning!!!
    - conditions:
      - condition: template
        value_template: '{{ 55.5 <= (trigger.payload | float) <= 200 }}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: PM2.5 at hazardous levels
          notification_id: pm2.5_warning
          title: Air quality warning!!!
  mode: single
- id: '1748949556532'
  alias: PM10
  description: ''
  triggers:
  - trigger: mqtt
    topic: home/sensor/pm10
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ 150 <= (trigger.payload | float) < 250 }}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: PM10 levels exceed safe limits
          notification_id: pm10_warning
          title: Air quality warning!!!
    - conditions:
      - condition: template
        value_template: '{{ 250 <= trigger.payload | float }}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: Fine dust (PM10) at hazardous levels
          notification_id: pm10_warning
          title: Air quality warning!!!
  mode: single
- id: '1748949758398'
  alias: CO2 warning
  description: ''
  triggers:
  - trigger: mqtt
    topic: home/sensor/co2
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ 1000 <= (trigger.payload | float) <= 3000 }}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: CO₂ concentration above safe limit
          notification_id: co2_warning
          title: Poor air circulation!!!
    - conditions:
      - condition: template
        value_template: '{{ 3000 < (trigger.payload | float) <= 10000 }}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: High CO₂ levels detected – ventilation activated
          notification_id: co2_warning
          title: CO2 Warning!!!
  mode: single
- id: '1748949853195'
  alias: CO warning
  description: ''
  triggers:
  - trigger: mqtt
    topic: home/sensor/co
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ 15 <= (trigger.payload | float) <= 50 }}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: CO levels exceed safe threshold – risk of poisoning
          notification_id: co_warning
          title: Warning!!!
    - conditions:
      - condition: template
        value_template: '{{ 50 < (trigger.payload | float) <= 300 }}'
      sequence:
      - action: persistent_notification.create
        metadata: {}
        data:
          message: High levels of carbon monoxide detected – evacuate immediately
          notification_id: co2_warning
          title: Danger!!!!
  mode: single
- id: '1748859184225'
  alias: Fall detection
  description: ''
  triggers:
  - trigger: mqtt
    topic: home/living/people/fall/state
    payload: '1'
  conditions: []
  actions:
  - action: persistent_notification.create
    metadata: {}
    data:
      message: Someone fell in the living room
      title: Fall Detection Warning!!!
  mode: single
- id: '1748956648036'
  alias: set action to humidifier
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - humidifier.living_room_humidifier
    above: 0
    below: sensor.humid_sensor
    attribute: humidity
  conditions: []
  actions:
  - action: mqtt.publish
    metadata: {}
    data:
      qos: '1'
      retain: true
      topic: home/living/humidity/action
      payload: humidifying
  mode: single
- id: '1748957956807'
  alias: set humid drying
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - humidifier.living_room_humidifier
    attribute: humidity
    above: sensor.humid_sensor
    below: 100
  conditions: []
  actions:
  - action: mqtt.publish
    metadata: {}
    data:
      qos: '1'
      retain: true
      topic: home/living/humidity/action
      payload: drying
  mode: single
- id: '1748958953795'
  alias: set drying bedroom 1
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - humidifier.bedroom_humidifier_1
    attribute: humidity
    above: sensor.humid_sensor
    below: 100
  conditions: []
  actions:
  - action: mqtt.publish
    metadata: {}
    data:
      qos: '1'
      retain: true
      topic: home/bedroom/1/humidity/action
      payload: drying
  mode: single
- id: '1748959014888'
  alias: set humidifying bedroom 1
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - humidifier.bedroom_humidifier_1
    above: 0
    below: sensor.humid_sensor
    attribute: humidity
  conditions: []
  actions:
  - action: mqtt.publish
    metadata: {}
    data:
      qos: '1'
      retain: true
      topic: home/bedroom/1/humidity/action
      payload: humidifying
  mode: single
- id: '1748959058628'
  alias: set drying bedroom 2
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - humidifier.bedroom_humidifier_2
    attribute: humidity
    above: sensor.humid_sensor
    below: 100
  conditions: []
  actions:
  - action: mqtt.publish
    metadata: {}
    data:
      qos: '1'
      retain: true
      topic: home/bedroom/2/humidity/action
      payload: drying
  mode: single
- id: '1748959088933'
  alias: set humidifying bedroom 2
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - humidifier.bedroom_humidifier_2
    above: 0
    below: sensor.humid_sensor
    attribute: humidity
  conditions: []
  actions:
  - action: mqtt.publish
    metadata: {}
    data:
      qos: '1'
      retain: true
      topic: home/bedroom/2/humidity/action
      payload: humidifying
  mode: single
- id: '1748959317369'
  alias: adjust humidity
  description: ''
  triggers:
  - trigger: mqtt
    topic: home/sensor/humidity
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ 20 < (trigger.payload | float) <= 30}}'
      sequence:
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/living/humidity/set
          payload: '60'
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/bedroom/1/humidity/set
          payload: '60'
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/bedroom/2/humidity/set
          payload: '60'
    - conditions:
      - condition: template
        value_template: '{{0 <= (trigger.payload | float) <= 20}}'
      sequence:
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/living/humidity/set
          payload: '40'
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/bedroom/1/humidity/set
          payload: '40'
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/bedroom/2/humidity/set
          payload: '40'
    - conditions:
      - condition: template
        value_template: '{{80 < (trigger.payload | float) <= 100}}'
      sequence:
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/living/humidity/set
          payload: '40'
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/bedroom/1/humidity/set
          payload: '40'
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/bedroom/2/humidity/set
          payload: '40'
    - conditions:
      - condition: template
        value_template: '{{ 70 < (trigger.payload | float) <= 80}}'
      sequence:
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/living/humidity/set
          payload: '50'
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/bedroom/1/humidity/set
          payload: '50'
      - action: mqtt.publish
        metadata: {}
        data:
          qos: '2'
          retain: true
          topic: home/bedroom/2/humidity/set
          payload: '50'
  mode: single
