
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# mqtt:
#   broker: mosquitto
#   port: 1883
mqtt:
  - sensor:
      name: "Temperature Sensor"
      state_topic: "home/sensor/temperature"
      unit_of_measurement: "°C"
      value_template: "{{ value | float }}"
