# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes/

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 6

webrtc:
  type: 'custom:webrtc-camera'
  streams:
    - url: 'rtsp://172.27.192.1:8554/webcam'
      name: HD
      mode: webrtc,webrtc/tcp,mse,hls,mjpeg  # stream technology, default all of them
      media: video  # select only video or audio track, default both

mqtt: 
  - sensor: !include_dir_merge_list components/sensors/
  # - binary_sensor: !include_dir_merge_list components/binary_sensors/
  - lock: !include_dir_merge_list components/locks/
  - light: !include_dir_merge_list components/lights/ 
  - climate: !include_dir_merge_list components/HVACs/ 
  - device_tracker: !include_dir_merge_list components/device_trackers/
  - switch: !include_dir_merge_list components/switches/
  - notify: !include_dir_merge_list components/notifications/