# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes/

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt: 
  - sensor: !include_dir_merge_list components/sensors/
  # - binary_sensor: !include_dir_merge_list components/binary_sensors/
  - lock: !include_dir_merge_list components/locks/
  - light: !include_dir_merge_list components/lights/ 
  - climate: !include_dir_merge_list components/HVACs/ 
  - device_tracker: !include_dir_merge_list components/device_trackers/