webrtc:
  ice_servers:
    - urls: [stun:stun.l.google.com:19302]
  ice_candidate_host: 172.27.192.1  # Thay bằng IP laptop
rtsp:
  listen: :8554
  transport: tcp
  read_buffer_size: 2048  # Tăng buffer nếu stream giật
  write_buffer_size: 2048
streams:
  webcam:
    - rtsp://172.27.192.1:8554/webcam  # Stream từ FFmpeg