- name: "Bedroom humidifier 2"
  unique_id: bedroom_humid_2
  device_class: "humidifier"
  
  current_humidity_topic: "home/sensor/humidity"

  command_topic: "home/bedroom/2/humidity/set"
  state_topic: "home/bedroom/2/humidity/state"

  target_humidity_command_topic: "home/bedroom/2/humidity/target/set"
  target_humidity_state_topic: "home/bedroom/2/humidity/target/state"

  mode_command_topic: "home/bedroom/2/humidity/preset/preset_mode"
  mode_state_topic: "home/bedroom/2/humidity/mode/state"
  
  action_topic: "home/bedroom/2/humidity/action" # off, humidifying, drying, idle
  
  modes:
    - "normal"
    - "eco"
    - "home"
    - "sleep"
    - "auto"
  qos: 1

  min_humidity: 30
  max_humidity: 80