- name: "Bedroom humidifier 1"
  unique_id: bedroom_humid_1
  device_class: "humidifier"
  
  current_humidity_topic: "home/sensor/humidity"
  command_topic: "home/bedroom/1/humidity/set"

  target_humidity_command_topic: "home/bedroom/1/humidity/set"
  target_humidity_state_topic: "home/bedroom/1/humidity/state"

  mode_command_topic: "home/bedroom/1/preset/preset_mode"
  mode_state_topic: "home/bedroom/1/humidity/mode/state"

  state_topic: "home/bedroom/1/humidity/state"
  action_topic: "home/bedroom/1/humidity/action" # off, humidifying, drying, idle
  
  modes:
    - "normal"
    - "eco"
    - "home"
    - "sleep"
    - "auto"
  qos: 1

  min_humidity: 30
  max_humidity: 80